a = input("Enter first value (a): ")
b = input("Enter second value (b): ")
c = input("Enter third value (c): ")
print("\nBefore swapping:")
print("a =", a)
print("b =", b)
print("c =", c)
print("\nAfter swapping:")
print("a =", c)
print("b =", a)
print("c =", b)
